<?php

/**
 * @file
 * Regenerates phpstan/extension-installer's GeneratedConfig at build time.
 *
 * extension-installer is a Composer *plugin*: it normally runs during
 * `composer install` and records which packages ship PHPStan extensions, so
 * PHPStan loads them automatically. Composer plugins do not run inside the Nix
 * sandbox, so the shipped stub survives with an empty EXTENSIONS list — and the
 * result is a PHPStan that has phpstan-drupal sitting in its vendor directory
 * and never loads it. Analysing a Drupal module with it then reports every core
 * class as "not found": a hundred lines that look like real findings.
 *
 * Reading vendor/composer/installed.json is exactly what the plugin does, so
 * doing it here produces the same file without needing the plugin to run.
 *
 * Usage: php generate-phpstan-extensions.php <vendor-dir>
 */

declare(strict_types=1);

$vendorDir = $argv[1] ?? NULL;
if ($vendorDir === NULL || !is_dir($vendorDir)) {
  fwrite(STDERR, "usage: {$argv[0]} <vendor-dir>\n");
  exit(2);
}
$vendorDir = rtrim((string) realpath($vendorDir), '/');

$installedFile = $vendorDir . '/composer/installed.json';
if (!is_readable($installedFile)) {
  fwrite(STDERR, "cannot read $installedFile\n");
  exit(1);
}
$installed = json_decode((string) file_get_contents($installedFile), TRUE, 512, JSON_THROW_ON_ERROR);
$packages = $installed['packages'] ?? $installed;

$extensions = [];
foreach ($packages as $package) {
  $includes = $package['extra']['phpstan']['includes'] ?? NULL;
  if (!is_array($includes) || $includes === []) {
    continue;
  }
  $name = $package['name'];
  // install-path is relative to vendor/composer/.
  $relative = $package['install-path'] ?? ('../' . $name);
  $absolute = realpath($vendorDir . '/composer/' . $relative);
  if ($absolute === FALSE) {
    fwrite(STDERR, "skipping $name: cannot resolve $relative\n");
    continue;
  }
  $extensions[$name] = [
    'install_path' => $absolute,
    'relative_install_path' => $relative,
    'extra' => ['includes' => array_values($includes)],
    'version' => $package['version'] ?? 'dev',
  ];
}

if ($extensions === []) {
  fwrite(STDERR, "warning: no PHPStan extensions found in $vendorDir\n");
}

$target = $vendorDir . '/phpstan/extension-installer/src/GeneratedConfig.php';
if (!is_dir(dirname($target))) {
  fwrite(STDERR, "phpstan/extension-installer is not installed; nothing to do\n");
  exit(0);
}

$export = var_export($extensions, TRUE);
$php = <<<PHP
<?php declare(strict_types = 1);

namespace PHPStan\ExtensionInstaller;

/**
 * Generated by drupal-nix-tools at build time, standing in for the Composer
 * plugin that cannot run inside the Nix sandbox.
 *
 * @internal
 */
final class GeneratedConfig
{

	public const EXTENSIONS = $export;

	public const NOT_INSTALLED = [];

	private function __construct()
	{
	}

}

PHP;

if (file_put_contents($target, $php) === FALSE) {
  fwrite(STDERR, "cannot write $target\n");
  exit(1);
}

fwrite(STDOUT, 'Registered ' . count($extensions) . " PHPStan extension(s): " . implode(', ', array_keys($extensions)) . "\n");
